### ISSUE TITLE
Fan does not start automatically whatever the temperature is...

### ISSUE THREAD

**Issue by Yume303** [myriadrf/LimeSDR-USB_GW#5]
Fan does not starts even on high temperatures, manually assuming 1 to 0xcc and 0xcd it starts.
HW rev: 1.4S

**Comment by vbuitvydas** [comment]
Can you clarify what do you mean by saying "high temperatures"? Does board temperature reach more than 55C? 
Use LimeSuiteGUI and check that temperature can be read from temperature sensor (Modules-> Board Controls). 
What GW version are you using?

**Comment by vbuitvydas** [comment]
Tested with latest GW (v2.23) and HW rev 1.4S, fan operates as described in:
 [https://wiki.myriadrf.org/LimeSDR-USB_hardware_description#Board_temperature_control](url)
