### ISSUE TITLE
Quartus 18.1 does not have DDR2 IPCore 

### ISSUE THREAD

**Issue by nome321** [myriadrf/LimeSDR-USB_GW#6]
Hello
i try to compile on quatus 18.1 but could not find DDR2 ip core now  DDR2 altmemphy supporting 
please help us how can we compile on Quartus 18.1
Thanks 
Nome

**Comment by 9600** [comment]
Hello,

You need to use Quartus 15.1.

**Comment by nome321** [comment]
Hi
yes I know 15.1 does supporting but officially intel altera obsolete 15.1 no more support from website
 thats why I am using 18.1
thanks
nome

**Comment by 9600** [comment]
I'm afraid we don't support recent versions.
